development:
  primary:
    adapter: sqlite3
    database: storage/development/primary.sqlite3
    schema_dump: false
  mytenant:
    adapter: sqlite3
    tenanted: true
    database: storage/development/%{tenant}.sqlite3
    schema_dump: false

